### ISSUE TITLE
Cannot install fullrmc on Linux

### ISSUE THREAD

**Issue by danpho** [bachiraoun/fullrmc#2]
I tried many times to install fullrmc on Linux. Unfortunately, I always received error messages shown below. Any suggestion and help would be highly appreciated.
    ERROR: Command errored out with exit status 1:
     command: /cm/shared/apps/python/2.7.16/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rZWIoV/fullrmc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rZWIoV/fullrmc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-rZWIoV/fullrmc/pip-egg-info
         cwd: /tmp/pip-install-rZWIoV/fullrmc/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rZWIoV/fullrmc/setup.py", line 23, in <module>
        raise Exception("must install cython first. Try pip install cython")
    Exception: must install cython first. Try pip install cython
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Numpy and cython have been installed.

**Comment by danpho** [comment]
cython and numpy have been installed.

**Comment by bachiraoun** [comment]
Have you solved this issue ? the error log is self-explanatory, you must have cython installed prior to installing fullrmc. 
It's an architecture choice to leave numpy and cython dependencies managed by the user to install. fullrmc doesn't install those for you but you must insure those dependencies are installed on your machine.
