### ISSUE TITLE
How to export PDF data instead of figure

### ISSUE THREAD

**Issue by danpho** [bachiraoun/fullrmc#3]
First, I have to say I just started to use fullrmc. The programs is more like a black box to me. I have limited Python programming experience. 

Following the examples given by the website, I could export figures to show the PDF fitting. However, I could not get the partial PDF data so I cannot plot the data by myself. The "blackbox" and limited parameter instruction confuse me. I do not know how to export the PDF data or other data instead of figures. Any further suggestion and help would be highly appreciated.

**Comment by bachiraoun** [comment]
please refer to the Q&A forum for additional questions.
